#pragma once
#include<tchar.h>
#include<Windows.h>
#include<iostream>
using namespace std;
#define SYMBOLIC_LINK L"\\\\.\\KBlankSlate"


#define CTL_PROCESS_PATH CTL_CODE(FILE_DEVICE_UNKNOWN,0x840,METHOD_BUFFERED,FILE_ANY_ACCESS)

typedef enum _OPERATE_TYPE_
{
	UNKNOWN = 0,
	ENUM_PROCESS,
	ENUM_PROCESS_MODULES,
	ENUM_PROCESS_HANDLES,
	ENUM_PROCESS_MEMORYS,
	READ_PROCESS_MEMORY,
	WRITE_PROCESS_MEMORY,
	MODIFY_PROCESS_MEMORY,
	TERMINATE_PROCESS,
	HIDE_PROCESS,
	PROTECT_PROCESS,
	UNPROTECT_PROCESS,
	ENUM_DRIVER_MODULE,
	START_PROC_MON,
	STOP_PROC_MON,
	GET_EVENTS_PROC_MON,
	CLOSE_HANDLE,
	START_FILE_MON,     // 启动文件监控
	STOP_FILE_MON,      // 停止文件监控
	GET_EVENTS_FILE_MON, // 获取文件事件
	START_THREAD_MON,      // 开始线程监控
	STOP_THREAD_MON,       // 停止线程监控
	GET_EVENTS_THREAD_MON, // 获取线程事件
	START_MODULE_MON,      // 开始映像加载监控
	STOP_MODULE_MON,       // 停止映像加载监控
	GET_EVENTS_MODULE_MON, // 获取映像加载事件
	PREVENT_MULTI_OPEN,    // 防止多开
	CANCEL_MULTI_OPEN,     // 取消防多开
	PROTECT_FILE_DELETE,   // 保护文件防删除
	UNPROTECT_FILE_DELETE, // 取消文件防删除保护
	PROTECT_FILE_MODIFY,   // 保护文件防修改
	UNPROTECT_FILE_MODIFY, // 取消文件防修改保护
	PROTECT_FILE_COPY,     // 保护文件防复制
	UNPROTECT_FILE_COPY,   // 取消文件防复制保护
	SERVICE_MAX
}OPERATE_TYPE;

#define CTL_BASE 0x800
#define CTL_CODE_NEITHER(i) CTL_CODE(FILE_DEVICE_UNKNOWN,CTL_BASE+i+0x100,METHOD_NEITHER,FILE_ANY_ACCESS)
#define MY_CTL_CODE CTL_CODE_NEITHER(1)

BOOL CommunicateDevice(PVOID InputBuffer, DWORD InputBufferSize, PVOID OutputBuffer, DWORD OutputBufferSize, DWORD* ReturnValue);

