#pragma once
#include<tchar.h>
#include<Windows.h>
#include<iostream>
using namespace std;
#define SYMBOLIC_LINK L"\\\\.\\KBlankSlate"


#define CTL_PROCESS_PATH CTL_CODE(FILE_DEVICE_UNKNOWN,0x840,METHOD_BUFFERED,FILE_ANY_ACCESS)

typedef enum _OPERATE_TYPE_
{
	UNKNOWN = 0,
	ENUM_PROCESS,
	ENUM_PROCESS_MODULES,
	ENUM_PROCESS_HANDLES,
	ENUM_PROCESS_MEMORYS,
	READ_PROCESS_MEMORY,
	WRITE_PROCESS_MEMORY,
	MODIFY_PROCESS_MEMORY,
	TERMINATE_PROCESS,
	HIDE_PROCESS,
	PROTECT_PROCESS,
	UNPROTECT_PROCESS,
	ENUM_DRIVER_MODULE,
	SERVICE_MAX
	
}OPERATE_TYPE;

#define CTL_BASE 0x800
#define CTL_CODE_NEITHER(i) CTL_CODE(FILE_DEVICE_UNKNOWN,CTL_BASE+i+0x100,METHOD_NEITHER,FILE_ANY_ACCESS)
#define MY_CTL_CODE CTL_CODE_NEITHER(1)

BOOL CommunicateDevice(PVOID InputBuffer, DWORD InputBufferSize, PVOID OutputBuffer, DWORD OutputBufferSize, DWORD* ReturnValue);

