#pragma once
#include<fltKernel.h>

//设备对象名称
#define DEVICE_NAME L"\\Device\\KBlankSlate"
//设备链接名
#define SYMBOLIC_LINK L"\\DosDevices\\KBlankSlate"
#define MAX_PATH 260
#define CTL_THREAD_INJECT CTL_CODE(FILE_DEIVCE_UNKNOWN,0x830,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define CTL_APC_INJECT CTL_CODE(FILE_DEIVCE_UNKNOWN,0x831,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define CTL_PROCESS_PATH CTL_CODE(FILE_DEVICE_UNKNOWN,0x840,METHOD_BUFFERED,FILE_ANY_ACCESS)

#define CTL_BASE 0x800
#define CTL_CODE_NEITHER(i) CTL_CODE(FILE_DEVICE_UNKNOWN,CTL_BASE+i+0x100,METHOD_NEITHER,FILE_ANY_ACCESS)
#define MY_CTL_CODE CTL_CODE_NEITHER(1)

typedef enum _OPERATE_TYPE_
{
	UNKNOWN = 0,
	ENUM_PROCESS,
	ENUM_PROCESS_MODULES,
	ENUM_PROCESS_HANDLES,
	ENUM_PROCESS_MEMORYS,
	READ_PROCESS_MEMORY,
	WRITE_PROCESS_MEMORY,
	MODIFY_PROCESS_MEMORY,
	TERMINATE_PROCESS,
	HIDE_PROCESS,
	PROTECT_PROCESS,
	UNPROTECT_PROCESS,
	ENUM_DRIVER_MODULE,
	START_PROC_MON,
	STOP_PROC_MON,
	GET_EVENTS_PROC_MON,
	CLOSE_HANDLE,
	START_FILE_MON,     // 启动文件监控
	STOP_FILE_MON,      // 停止文件监控
	GET_EVENTS_FILE_MON, // 获取文件事件
	START_THREAD_MON,      // 开始线程监控
	STOP_THREAD_MON,       // 停止线程监控
	GET_EVENTS_THREAD_MON, // 获取线程事件
	START_MODULE_MON,      // 开始映像加载监控
	STOP_MODULE_MON,       // 停止映像加载监控
	GET_EVENTS_MODULE_MON, // 获取映像加载事件
	PREVENT_MULTI_OPEN,    // 防止多开
	CANCEL_MULTI_OPEN,     // 取消防多开
	SERVICE_MAX
}OPERATE_TYPE;

typedef NTSTATUS(*LPFN_SERVICEADDRESS)(PVOID InputBuffer, ULONG InputBufferLength, PVOID OutputBuffer, ULONG OutputBufferLength, ULONG* ReturnValue);
NTSTATUS CommunicateNeitherControl(PVOID InputBuffer, ULONG InputBufferLength, PVOID OutputBuffer, ULONG OutputBufferLength, ULONG* ReturnValue);
LPFN_SERVICEADDRESS GetServiceAddress(OPERATE_TYPE OperateType);
