#pragma once
#include<fltKernel.h>

//设备对象名称
#define DEVICE_NAME L"\\Device\\KBlankSlate"
//设备链接名
#define SYMBOLIC_LINK L"\\DosDevices\\KBlankSlate"
#define MAX_PATH 260
#define CTL_THREAD_INJECT CTL_CODE(FILE_DEIVCE_UNKNOWN,0x830,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define CTL_APC_INJECT CTL_CODE(FILE_DEIVCE_UNKNOWN,0x831,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define CTL_PROCESS_PATH CTL_CODE(FILE_DEVICE_UNKNOWN,0x840,METHOD_BUFFERED,FILE_ANY_ACCESS)

#define CTL_BASE 0x800
#define CTL_CODE_NEITHER(i) CTL_CODE(FILE_DEVICE_UNKNOWN,CTL_BASE+i+0x100,METHOD_NEITHER,FILE_ANY_ACCESS)
#define MY_CTL_CODE CTL_CODE_NEITHER(1)

typedef enum _OPERATE_TYPE_
{
	UNKNOWN = 0,
	ENUM_PROCESS,
	ENUM_PROCESS_MODULES,
	ENUM_PROCESS_HANDLES,
	ENUM_PROCESS_MEMORYS,
	READ_PROCESS_MEMORY,
	WRITE_PROCESS_MEMORY,
	MODIFY_PROCESS_MEMORY,
	TERMINATE_PROCESS,
	HIDE_PROCESS,
	PROTECT_PROCESS,
	UNPROTECT_PROCESS,
	ENUM_DRIVER_MODULE,
	SERVICE_MAX

}OPERATE_TYPE;

typedef NTSTATUS(*LPFN_SERVICEADDRESS)(PVOID InputBuffer, ULONG InputBufferLength, PVOID OutputBuffer, ULONG OutputBufferLength, ULONG* ReturnValue);
NTSTATUS CommunicateNeitherControl(PVOID InputBuffer, ULONG InputBufferLength, PVOID OutputBuffer, ULONG OutputBufferLength, ULONG* ReturnValue);
LPFN_SERVICEADDRESS GetServiceAddress(OPERATE_TYPE OperateType);
